[env]
PROJECT_NAME = "copilot-playbook"

[tools]
gh = "2.92.0"
gitversion = "6.7"
python = "3.14"
"pipx:pre-commit" = "4.6"

[task_config]
includes = [
  "git::ssh://git@github.com/jterral/my-mise-tasks.git//tasks/precommit?ref=v2",
]
