name: release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: gittools/actions/gitversion/setup@v4.3.2
        with:
          versionSpec: "6.5.1"

      - id: version_step
        uses: gittools/actions/gitversion/execute@v4.3.2

      - name: Version Info
        run: |
          echo "Version: ${{ steps.version_step.outputs.GitVersion_SemVer }}" >> $GITHUB_STEP_SUMMARY

      - name: 🏷️ Tag release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "v${{ steps.version_step.outputs.GitVersion_SemVer }}"
